# Generated by Django 5.2.5 on 2025-08-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('legenda', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
